all:exec

#nullp:NullPointer.c
#	g++  -g -Wall NullPointer.c  -o nullp   
#
#outb:OutBound.cpp
#	g++  -g -Wall 	OutBound.cpp  -o outb   

#exec IS Main for show
exec:exeCore.cpp
	g++  -g -Wall 	exeCore.cpp  -o exec   


clean:
	rm -f  exec