all:thread  

thread:threadLock.c
	gcc   -g -Wall threadLock.c  -o thread   -lpthread


#tl:tl.c
#	gcc   -g  -Wall tl.c  -o tl   -lpthread
#
#tll:tll.c
#	gcc   -g  -Wall tll.c  -o tll   -lpthread
clean:
	rm -f thread tl   tll