
"  很好很强大的vimrc（带注释版） https://blog.csdn.net/fryingpan/article/details/40183197
" 设置swp undo backup 目录

set dir=f:\vimtmp\swp
set udir=f:\vimtmp\undo
set bdir=f:\vimtmp\backup
" 设置配色方案
colorscheme  darkblue
"显示行号
set number

"文件编码
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,cp936,gb2312,big5,euc-jp,euc-kr,latin




syntax on                   " 自动语法高亮
set cursorline              " 突出显示当前行
set ruler                   " 打开状态栏标尺
set incsearch               " 输入搜索内容时就显示搜索结果
set hlsearch                " 搜索时高亮显示被找到的文本

" ctags 设置
set tags=tags;
set autochdir

" tab 设置为4个空格
set ts=4
set expandtab
set autoindent
