
"  很好很强大的vimrc（带注释版） https://blog.csdn.net/fryingpan/article/details/40183197
" 设置swp undo backup 目录

set dir=f:\vimtmp\swp
set dir=f:\vimtmp\undo
set dir=f:\vimtmp\backup
" 设置配色方案
colorscheme  darkblue
"显示行号
set number
