all:  ssx ccx
#sst:pthread_server.c
#	gcc -g -Wall pthread_server.c  -o sst  -lpthread
#
#cct:pthread_client.c
#	gcc  -g pthread_client.c   -o cct

#ss:server.c
#	gcc  -g server.c  -o ss  
#
#cc:client.c
#	gcc  -g client.c  -o cc
	
	
#ssx ccx is main for show
ssx:s.c
	gcc  -g s.c  -o ssx

ccx:c.c
	gcc  -g c.c  -o ccx

clean:
	rm -f ss  cc  ssx ccx 	
#	rm -f ss	cc  sst cct